### ISSUE TITLE
There is no data set named 'tapwater' in library 'statsr'.

### ISSUE THREAD

**Issue by hongqiangzhou** [StatsWithR/book#61]
Please check the library 'statsr'. I failed to compile the book due to this issue.

**Comment by merliseclyde** [comment]
At this time, the `tapwater` data are in the branch BayesFactor of the `statsr` package as some functionality has changed and the master versions is being used in the live Coursera course.  Please see the updated README for installation.  Both the book and this branch are for support of the next release of the Coursera course.
